services:
  - type: web
    name: badminton-booking-backend
    env: node
    plan: free
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    # Add these for better reliability
    buildFilter:
      paths:
        - Backend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 